language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6
            - ninja-build
            - libphysfs-dev
            - libsquish-dev
            - libglm-dev

git:
  submodules: false

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - git submodule update --init --recursive
  - mkdir -p build
  - cd build
  - cmake -GNinja -DZENLIB_BUILD_EXAMPLES=On -DZENLIB_BUILD_TESTS=On ..
  - ninja
  - cd ../tests
  - ../build/tests/test_vdfs
